FROM node:20-slim AS builder
WORKDIR /app
COPY package.json .
RUN npm install --legacy-peer-deps && npm install ajv@^8.11.0
COPY src/ ./src/
COPY public/ ./public/
RUN npm run build

FROM nginx:alpine AS runtime
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]